### PR TITLE
First approach to events.

### PR DESCRIPTION
**Pull request by skasi7**
PR for issue #781.

These are the interesting changes:
* (event_dispatcher.py) Added to handle event dispatching.
* (addin.xlam/Config.bas) Fixed issue with GetWorkbookDirectoryConfigFilePath when ActiveWorkbook is Nothing.
* (addin.xlam/Main.bas) Fixed issue with XLPyCommand when ActiveWorkbook is Nothing.
* (main.py) Added caller_address and caller methods to Range class to retrieve the caller address and caller range.
* (server.py) Alternative kill procedure (win32con.WM_QUIT message). Event method to process events from addin. Disabled events during CallUDF and Event methods to avoid recursive events. New protected method _TraceExc to trace exceptions to log and/or message box.
* (udfs.py) Added xlevent and xleventexc decorators to create event handler UDFs. Removed BOOK_CALLER setup inside call_udf (moved to CallUDF and Event methods from server.py).

Also an example of use were added:
* Steps to reproduce:
  * Open Excel
  * Close default workbook
  * Load event.xlsm
  * Import UDFs (will connect event handlers), multiple imports won't trigger multiple times.
* Things to play with:
  * Click on any, cell => Sets value to X (note that this not triggers the WorksheetChange event)
  * Modify any cell => adds 1 if it's numeric (shallowed exception if not)
  * Change sheet => A message box will show.
  * Close and open events.xlsm (don't work with other workbooks due to #787) => A message box will show (lack of creativity).

TODO:
* Add more event handlers (as needed/requested).

Any comment will be welcomed.

### CODE REVIEW

**Comment by fzumstein** [comment]
thanks! It might take me a few days though until I get around to take a closer look...

**Comment by skasi7** [comment]
Feel free to ask me whatever you don't catch (my code can be overcomplicated sometimes).

**Comment by fzumstein** [comment]
finally got to look at this! I think it's great, only two questions for now:

* is it possible to setup a spreadsheet so it connect the handlers automatically when opening it instead of having to click on import udfs? 
* On these samples: 

```
@xw.event('SheetSelectionChange')
def on_sheet_selection_change(xl_sheet, xl_range):
    xl_range.Value = 'X'
```

is it possible to use the xlwings range object here instead of the pywin32 one?

I've pushed your branch here so to see the vba diffs: https://public.xltrail.com/#/workbook/github.com%2FZoomerAnalytics%2Fxlwings.git%2Fxlwings%2Faddin%2Fxlwings.xlam/diff/b92eca84e5d101b7cd7fc894737bf88cd9dcc0f6

**Comment by skasi7** [comment]
Glad to read that you like it! Answering your questions:
* The problem is to know the location of the UDFs module. If it's known, you can add the ImportPythonUDFs macro to the Auto_Open Sub (executed when a spreadsheet is opened manually).
* The reason behind not using xlwings objects was I usually perform simple operations. But it's perfectly possible to replace the native objects with xlwings equivalents in the event_dispatcher.py before calling the user defined callbacks.

Thank you for the diff in xltrail (very cool tool BTW), It's very difficult to see these changes.

**Comment by fzumstein** [comment]
* Regarding the location of UDF module: I don't see the difference to standard UDFs, i.e. you could set the location of the module (i.e. PYTHONPATH & UDF Modules combo) either via global config/ribbon or via `xlwings.conf` sheet if you don't use the default (same name, same directory).

* Is there a reason why you would use Auto_Open instead of Workbook_Open?

* Would you have time to add the changes for the xlwings object? since you can always fall back to `.api` it would be more in line with the rest of the library.

**Comment by skasi7** [comment]
* You're right about the location. The reason behind using Auto_Open is that it's only called when the workbook is opened manually (not programatically, although can be fired if needed). I think it's safer.
* Yeah, sure, I can change the callbacks to pass xlwings objects. I agree is more consistent, but sometimes I'm a little lazy ;).

**Comment by fzumstein** [comment]
Actually, I've setup your fork on xltrail so you can see the diff automatically: https://public.xltrail.com/#/?path=github.com%2Fskasi7%2Fxlwings.git&branch=events

**Comment by skasi7** [comment]
Finally I've managed to take some time to change the arguments of the callbacks from pywin32 instances to xlwings objects. If you have questions, don't hesitate to comment.

**Comment by skasi7** [comment]
My decorators mimic the others from xlwings. The first time I saw them I was also intrigued, but never asked. Maybe Felix can enlighten us.

**Comment by fzumstein** [comment]
well, it's the same as further down where it's called `inner` instead of `real_decorator`: it's used so the decorator can accept args. It maybe confusing because the instance with `real_decorator` are indeed just dummies so that the functions can still be used on Mac.

**Comment by fzumstein** [comment]
Ok so I had another look at it with @ericremoreynolds who did the UDF part. We would like to simplify that to generate the event wrappers only in the workbook itself and only for the ones that are used. This should be doable within the `import_udfs` function and written directly to the workbook using something along these lines (just a sample as a reminder): 

```
Sub Something()
    Workbooks("...").VBProject.VBComponents("ThisWorkbook").CodeModule.AddFromString ("Private Sub Workbook_SheetChange(ByVal Sh As Object, ByVal Target As Range)" + vbCrLf + "Application.StatusBar = Target.Address" + vbCrLf + "End Sub")
End Sub
```
https://www.ozgrid.com/forum/forum/help-forums/excel-general/16556-importing-exported-modules-into-sheet-code-modules-and-thisworkbook-module

**Comment by skasi7** [comment]
Sounds great! The more autogenerated VBA code, the better. And creating only the needed ones is a neat touch.

**Comment by lehajam** [comment]
Hi guys, 

Just would like to know if there have been any update on this as I would like to subscribe to server sent events from a UDF ?

Thanks

**Comment by fzumstein** [comment]
what do you mean by server sent events? This PR is about Excel workbook/sheet events.

**Comment by richbeales** [comment]
Hi, is there any timescale/further progress on this?

**Comment by fzumstein** [comment]
Hi @richbeales, thanks for the bump, we're planning to implement this as part of xlwings PRO in 2020.

**Pull request closed without merging**
