### PR TITLE
add a context manager to easily "freeze" excel when running code (issue #254)

### PR DESCRIPTION
**Pull request by sdementen**
still need to update documentation about release version (is this automated ?)

### CODE REVIEW

**Comment by fzumstein** [comment]
Nothing automated here neither, but it's OK the way you have it, I ll adjust to the working version whenever I ll merge.

**Comment by fzumstein** [comment]
I would like to keep the kwargs of `freeze` closer to Excel's version: 

`calculation_manual` instead of `calculation`
`enable_events` instead of `events`
`screen_updating` instead of `screen`
`display_alerts` instead of `alerts`

I think it makes it much easier to adopt when coming from VBA. In any case, currently `calculation=True` is highly confusing: I would expect it to actually *do* calculations when I see that statement.

**Comment by sdementen** [comment]
As the function is called "freeze", it make more sense to me to write "freeze(calculation=True)" to mean "do freeze the calculation". And in this spirit, the name "events" instead of "enable_events" is also logic (meaning "freeze events"). Besides, the excel naming is not that consistent (why do not we have "enable_alerts" instead of "display_alerts" ?).

If you want to have the original names, the context manager should not be called "freeze" but something like "set_behavior" and then you can repeat all the names as in excel ("enable_events", etc). I would then avoid a calculation_manual as it is not consistent with excel (that uses simply calculation).

But I think that, in general, the "freeze" functionality is the one needed, ie, we want normally to have Excel functioning as usual and then, temporarily (in a context manager), freeze some of this dynamic behavior to do some heavy operations.

**Comment by fzumstein** [comment]
Ok fair enough. However, Eric and I were thinking about moving such non-core functionality into something like an `ext` subpackage: `from xlwings.ext import freeze`

**Comment by sdementen** [comment]
Could be an option indeed but then it would not be a method of Application
(no monkey patching) so we could not write

with app.freeze(events=True):

but we would have to write

with freeze(app, events=True):

which IMO looks less readable (but not that a big deal)


On Wednesday, December 2, 2015, Felix Zumstein <notifications@github.com>
wrote:
> Ok fair enough. However, Eric and I were thinking about moving such
non-core functionality into something like an ext subpackage: from
xlwings.ext import freeze
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/NB9radvuYpnFdL2n167aAtbOSRaMQRhbZRY3wEB6uWKeQUP6bhJjwQr9CjEjAReqrhr1rdqm7uA3mXuHR80DMMLwnygKZKCpXtKZ_rEHKTCkvBJ8DRdW-bwc5F7Us3QiYaULNmXa30ws-P9WMypfZyPIUVFMXQ=s0-d-e1-ft#https://github.com/notifications/beacon/ABPpdt2OBvveub74_4CKGc-5tDDhIb77ks5pLr4jgaJpZM4GQrhI.gif
>

**Comment by ericremoreynolds** [comment]
Hey Sebastien,

why would we necessarily exclude monkey patching?

I don't see that it would create so many problems - to use `app.freeze` u just need to make sure that you have done `import xlwings.ext.freeze` at some point.

**Comment by sdementen** [comment]
hello Eric,

I have no fundamental problem with monkey patching when related to obscure
behind the back behavior to tweak.

But I wonder if for user functionalities, this wouldn't be surprising. If
he/she sees a "with app.freeze(events=True):" in some code on stackoverflow
and tries it at home, he will be welcomed by a "attribute does not exist"
and it would take (i think) some time to see that it is a side effect of an
import statement.

On the hand, if we want to provide a way to "extend" the core xlwings
functionalities but in some integrated way (avoiding for instance code like
"with freeze(app, events=True):"), it may be the only way to do it.

Now, the "freeze" functionality is more a "core" one as I think (but I may
be wrong) it is the only "use case" for tweaking the 4 behavioral functions
(enable_events, displayalerts, ...). At least, in my use, I always change
these because I want them to be "disabled/frozen" during some operation and
then be "enabled/unfrozen" directly after (otherwise, the behavior of Excel
starts to be quite weird).

**Comment by ericremoreynolds** [comment]
Ok let's go for `with freeze(app, events=True)` then.

Sorry to insist on the idea of keeping it a separate in an `xlwings.ext` module, the idea is that since we're still actively developing xlwings, we'd rather not have this within the perimeter of code we're directly responsible for. Keeping it in an `ext` module marks it as being contributed code.

In fact, if it's ok, in practice you can maintain this code. Please put your name and details in a comment at the top of the source file (something like [this](https://github.com/git/git/blob/master/contrib/subtree/git-subtree.sh)) and then should changes to the xlwings API break the code, you can fix it via a PR.

And of course we can repeat this mechanism for any other features you'd like to contribute - this should help us accept them more quickly.

How does that sound?

**Comment by sdementen** [comment]
OK, let's have a try !

But I could not follow exactly what was meant by the document on subtrees
you linked so I am a bit lost on what to do.

Would it work like this:
1) I create a repo on my github named sdementen/xlwings.ext.UIHelper (and
so now I need to find a name for such extension !)
2) you link it from the original xlwings repo
is that more or less what happens ? (I have found this
https://help.github.com/articles/about-git-subtree-merges/ and read it
quickly)

What happens with testing, the release to PyPI and the documentation ? is
it more or less integrated with xlwings or totally separated ? if
separated, it may be a bit overkill for freeze ;-) but adapted for more
heavy-weighted extensions.

Do you know if it is that way that sqlalchemy.ext or SDL2.ext works ?

**Comment by fzumstein** [comment]
Hey Sebastien,

Eric was only referring to the file structure, not the content of subtree. You don't have to change anything in how you contribute via PR. Just move things into `ext` and put your name at the top of the module.

**Comment by sdementen** [comment]
ok, got it ! I'll do that.

**Comment by ericremoreynolds** [comment]
Yes, sorry! The subtree link was just an example of putting your name at
the top of the file in a comment.

**Comment by ericremoreynolds** [comment]
Just to show that contributed code is managed this way in other open source
projects too...

**Comment by sdementen** [comment]
Eric, could you have a look at the new commit ? does it go in the right direction ?

**Comment by ericremoreynolds** [comment]
Hi Sebastien,

Yes that's definitely the sort of thing I had in mind.

Thanks for all the hard work, as soon as have time we'll merge your PR.

Eric

**Comment by sdementen** [comment]
Do you plan for ext code to be imported explicitly by the user to get access to it ? Or would you import the ext code directly (and there monkey patching would make sense) to make it transparent to the user (but nevertheless keep the code base separated)?
I was thinking the first scenario when writing previous post. We're you thinking the second one ?

**Comment by wkschwartz** [comment]
This looks like a nice feature that hasn't received any attention in a couple years. What next steps can I help with to get this merged?

**Comment by sdementen** [comment]
You can look at issue #254 as there were some new comments re the API. 
And there is the discussion on the fact it should be in an extension package. I feel to be a bit overkill but it is up to Felix/Eric to decide

**Comment by fzumstein** [comment]
replaced by #1658

**Pull request closed without merging**
