### PR TITLE
First approach to object cache.

### PR DESCRIPTION
**Pull request by skasi7**
PR for issue #555.

Note: The branch of this PR is a branch of the events branch, so contains changes from both features. The only file modified in both is __init__.py (importing the new stuff to the main namespace).

These are the interesting changes:
* (object_cache.py) The new Object cache.

Also an example of use were added:
* Steps to reproduce:
  * Open Excel
  * Close default workbook
  * Load object_cache.xlsm
  * Import UDFs (will connect the object cache event handlers),
* Things to play with:
  * See the formulas inside the cells forming the table.
  * Note that the last instance is an aggregation of instances returning another instance.
  * See the amount of objects and references hold by the cache.

TODO:
* Removal of references (currently the only approach to remove references is removing them, closing Excel and start again). This will imply handling more events and updating the object cache accordingly (see https://www.pyxll.com/docs/examples/objectcache.html).

Any comment will be welcomed.

### CODE REVIEW

**Comment by skasi7** [comment]
I changed the event handlers inside objects_cache.py to match the new arguments passed (xlwings objects). So this implementation is also ready for review.

**Comment by fzumstein** [comment]
Awesome thanks!

**Comment by audetto** [comment]
I think this would be a great addition to xlwings.
One question I have is:

**Assume, one cannot hook Excel events, how good / bad the rest of the idea would be?**

I see 2 events are intercepted: ``Open`` and ``NewSheet``.

I was surprised by this choice: I thought that one needs to hook the ``Close``, ``Delete`` or ``Calculate``, because they signal when cells die.

So, what would be the consequences of missing ``Open`` and ``New``? 

- a previous xls had registered an object at some cell ``A.xls.Shee1.D1``
- it is closed
- a new one (with the same name) is opened which does not define ``A.xls.Shee1.D1``, but the old object is still available?

Is this the main issue that events try to solve?

I am only commenting this as I wonder if hooking events does not add a whole new complexity to ``xlwings``?

**Comment by fzumstein** [comment]
This has now also been implemented in xlwings Server, see: https://github.com/xlwings/xlwings/issues/555#issuecomment-2289741057

**Pull request closed without merging**
