### PR TITLE
xlwings Server: fix threading issue with and properly decode image_st…

### PR DESCRIPTION
**Pull request by fzumstein**
…ring so it works with pyscript

### CODE REVIEW

**Comment by gdementen** [comment]
FWIW, the fix to this issue broke my application, which uses both matplotlib, xlwings and Qt. It took me several hours to find the cause of the issue because the failure was in matplotlib code, not in xlwings.

**Comment by gdementen** [comment]
Wouldn't it be possible to do that only in the "server" part, and not in utils, so that when you "import xlwings" from a Python script, you don't have such an unexpected side-effect?

**Comment by fzumstein** [comment]
What's the error message you're getting?

**Comment by fzumstein** [comment]
or...wha't the exact issue? are you embedding matplotlib in qt and it's requiring a different backend?

**Comment by gdementen** [comment]
The error I was getting is not very interesting IMO:
```python
Traceback (most recent call last):
[...]
  File "[...]\larray_editor\utils.py", line 302, in show_figure
    figure.canvas.manager.window is not None):
AttributeError: 'FigureManagerBase' object has no attribute 'window'
```
and I did not understand what was happening until I saw the changed line in xlwings code and I realized my matplotlib figure manager has always been Qt-based and after the change in xlwings, it was not anymore.

My use case is indeed a Qt application which uses both matplotlib (and thus requires its QtAgg backend) and xlwings. This is not something everybody does... but can't this change cause problems to more classic scripts using both matplotlib (via pyplot module for example) and xlwings? I think the default backend for matplotlib is usually Qt and currently "import xlwings" changes that, which is unexpected (at least for me).

FWIW, I just fixed the issue in my code by using `matplotlib.use('QtAgg')`, but since this is a global thing, I fear this is will depend on the order of imports, so the fix might be brittle, especially because my application can also be called from within user scripts which could use xlwings too.

**Comment by fzumstein** [comment]
Got it, I'll remove it from there: https://github.com/xlwings/xlwings/issues/2484

**Comment by gdementen** [comment]
Thanks a lot

**Pull request merged**
