### PR TITLE
Document translation of simplified Chinese.

### PR DESCRIPTION
**Pull request by efreeway**
Translate most of the rst files into simplified Chinese, except parts of whatsnew.rst.
[docs_zh-cn-2020-01-01.zip](https://github.com/xlwings/xlwings/files/4014151/docs_zh-cn-2020-01-01.zip)

### CODE REVIEW

**Comment by fzumstein** [comment]
hi @efreeway! thanks for that! Do you mind to commit the po files directly to `/docs/locales/zh-cn/LC_MESSAGES`? See https://github.com/xlwings/xlwings/blob/master/DEVELOPER_GUIDE.md#docs and the other currently existing translations: https://github.com/xlwings/xlwings/tree/master/docs/locales
Let me know if you have any questions! Thanks!

**Comment by efreeway** [comment]
Thanks for your information and let me try.

**Comment by efreeway** [comment]
> I have translate most of .po files except api.po and license.po. Below is a zip file of these translated po file. I have tried to "git puss origin master " but got an Eroor. 
(ERROR: Permission to xlwings/xlwings.git denied to efreeway.)

Please check the files below. Thanks.
[zh_CN.zip](https://github.com/xlwings/xlwings/files/4022060/zh_CN.zip)

**Comment by fzumstein** [comment]
Hey @efreeway you will need to push again to your own branch on `efreeway/xlwings`, not to the upstream `xlwings/xlwings`

**Comment by fzumstein** [comment]
Looks good now except `docs_zh-cn.rar` can you delete that again?

**Comment by efreeway** [comment]
> Looks good now except `docs_zh-cn.rar` can you delete that again?

docs_zh-cn.rar has been deleted, thanks.

**Comment by fzumstein** [comment]
awesome, that's live now: https://docs.xlwings.org/zh_CN/latest/

**Pull request merged**
