### PR TITLE
Added UDF import fallback to prevent unreproducable Automation error 440

### PR DESCRIPTION
**Pull request by fzumstein**
…error 440

### CODE REVIEW

**Comment by Colin-b** [comment]
Won't this change make it impossible for other application to have their own version of xlwings ? I mean, I personally use another xlam with its own xlwings_udfs. This change will not allow that anymore, as it will require the xlam to be named as xlwings. Or am I mistaken ?

**Comment by fzumstein** [comment]
better now?

**Comment by Colin-b** [comment]
It's better, but I don't know how it will behave if the user have xlwings addin installed, and another xlam "embedding" xlwings ?  Not so sure how it would behave right now so I guess it's ok :-)

**Comment by fzumstein** [comment]
shoud be good now

**Pull request merged**
